name: KeepInventory
main: KeepInventory\Main
version: 1.0.1
api: [3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
description: "Function to Keep Inventory"
website: https://www.pizyds.com/
