name: PiZYDS-KeepInventory
main: KeepInventory\Main
version: 1.0.0
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
description: "Helps to Keep Inventory"
website: https://www.pizyds.com/
